Desktop Version
mhassa204/Capstone-Fifa2022 pull request #2
Opened 2023-08-09 21:14 UTC by mhassa204

In this PR desktop version with home page and about page has been implemented. The hamburger menu also has been implemented.

2023-08-09 22:30 UTC, DuaneDave requested changes
Hi @mhassa204 👋, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-08-09 22:30 UTC, DuaneDave commented on index.html
> +        </ul>
According to the design, there should be a footer on the homepage and the background is expected to be light coloured according to the colour scheme of the given template. Kindly add this in order to make your design match that on Behance.

2023-08-09 22:30 UTC, DuaneDave commented on about.html
> +    </footer>
The background color for the footer on the About page is expected to be dark colored according to the provided color scheme in the given template. Kindly update the color in order to make your design match the given template.

Also, ensure to reduce the height of the footer to make it match that on Behance, in addition, i would want you to work on the spacing of the text from the end of the container

<img width="960" alt="image" src="https://github.com/mhassa204/Capstone-Fifa2022/assets/84930355/7bfa3cd1-5951-450a-9c50-c59de5e239cf">

2023-08-09 22:30 UTC, DuaneDave commented on index.html
> +            <p class="mt1">@ Lusail Stadium, Qatar</p>
I can't seem to spot where the image on the UI is coming from hence, I recommend finding it and removing it from the UI, both for the home and about page as it is cluttering the UI and it should not be part of the UI according to the template.

<img width="901" alt="image" src="https://github.com/mhassa204/Capstone-Fifa2022/assets/84930355/b9ad1277-083f-4c12-892f-90dcb976492a">

2023-08-09 22:30 UTC, DuaneDave commented on index.html
> +        <li class="aligned"><img src="./images/flags/1x1/sa.svg" alt=""><h3>Saudi Arabia</h3></li>
According to the design, there are five cards in the section of the homepage, I recommend adding two more in order to stick with the composition and organization of the given design

<img width="955" alt="image" src="https://github.com/mhassa204/Capstone-Fifa2022/assets/84930355/8d3c0d72-f098-45f1-b3f3-72b48a802222">

2023-08-09 22:30 UTC, DuaneDave commented on index.html
> +                <div>
According to the requirements, there should be six cards here and the cards should be rendered dynamically using javascript instead of hardcoding it. I recommend adding two more cards and creating this section dynamically in order to stick with the requirements.

<img width="958" alt="image" src="https://github.com/mhassa204/Capstone-Fifa2022/assets/84930355/1a83c6dc-3752-4fc2-a105-95b65cf19884">

2023-08-09 22:30 UTC, DuaneDave commented on about.html
> +              <a  href="">Program</a>
Please ensure to hide the hamburger on the desktop view in order to not clutter up the navigation with unnecessary item

<img width="960" alt="image" src="https://github.com/mhassa204/Capstone-Fifa2022/assets/84930355/f6f5eae8-8935-4667-b822-b19770756764">

2023-08-10 08:38 UTC, mhassa204 commented on index.html
> +            <p class="mt1">@ Lusail Stadium, Qatar</p>
@DuaneDave It's not coming up on my side

2023-08-10 09:05 UTC, danmainah commented on about.html
> +    </footer>
- [ ] [optional] @mhassa204 Great work implementing the change requested, however, it would be nice moving the logo and copyright text to the center to match the design given, kindly check the comparison below

Behance Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://github.com/mhassa204/Capstone-Fifa2022/assets/61408860/6542940c-40d0-44ad-a7e1-8808da23360c)  |  ![image](https://github.com/mhassa204/Capstone-Fifa2022/assets/61408860/641b5bfb-7948-4335-9de0-f25d5d8a805d)

2023-08-10 09:12 UTC, danmainah commented on index.html
> +            <p class="mt1">@ Lusail Stadium, Qatar</p>
- [ ] @mhassa204 Great work implementing the change requested, however, the reviewer meant the colored area highlighted below is making your design not match the Behance design, check the comparison in the homepage below, kindly consider removing the color in both home and about page.

Behance Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://github.com/mhassa204/Capstone-Fifa2022/assets/61408860/1fb62b92-50e2-4bda-8ddc-cd3b479703ed)  |  ![image](https://github.com/mhassa204/Capstone-Fifa2022/assets/61408860/e2bfb426-a63e-4267-8448-57a26f7f38b4)

2023-08-10 09:18 UTC, danmainah commented on index.html
> +            </li>
- [ ] @mhassa204 Great work implementing the change requested, however, the whole list should be generated dynamically using javascript kindly move the remaining two players to be rendered dynamically.

2023-08-10 09:56 UTC, mhassa204 commented on index.html
> +            <p class="mt1">@ Lusail Stadium, Qatar</p>
@danmainah Please explain a little bit, i don't understand this point.

2023-08-10 09:58 UTC, mhassa204 commented on index.html
> +            </li>
@danmainah The whole list should be generated for desktop version only? Please explain as for the mobile there are already two list items before the More Button.

2023-08-10 10:13 UTC, danmainah commented on index.html
> +            <p class="mt1">@ Lusail Stadium, Qatar</p>
@mhassa204 as the previous reviewer noted the area I have highlighted below makes your design differ from the design given 
![image](https://github.com/mhassa204/Capstone-Fifa2022/assets/61408860/e3411240-029c-4c9c-a46a-9421e45917c5)

2023-08-10 10:14 UTC, danmainah commented on index.html
> +            </li>
> @danmainah The whole list should be generated for the desktop version only. Please explain as for the mobile there are already two list items before the More Button.

@mhassa204 All of it should be generated dynamically, for mobile its an optional extension where you create a javascript function to handle display of only 2 players and display the rest on clicking more

2023-08-10 10:31 UTC, mhassa204 commented on index.html
> +            <p class="mt1">@ Lusail Stadium, Qatar</p>
@danmainah but i can't see like this on my side

2023-08-10 11:44 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @mhassa204, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## To Highlight 👍

- Descriptive Pull Request title and summary. ✔️
- Project contains a Home & About page ✔️
- hamburger menu on the left side ✔️
- Follow [Cindy Shin](https://www.behance.net/adagio07) design template ✔️
- Good use of Github flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 12:13 UTC, merged